# Site settings
author: M. Real
title: Human tries ruby, ruby tries human
header-img: img/home-bg.png
email: melissa.real@hotmail.com
copyright_name: M. Real
description: > # this means to ignore newlines until "baseurl:"
  My journey into programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  melzreal

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
